version: '3'
services:
  node:
    container_name: server
    restart: always
    build: .
    ports:
      - '80:5000'
    links:
      - mongo
  mongo:
    container_name: database
    image: mongo
    ports:
      - '27017:27017'
